# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12q8W6l-TMn4ZkJn_TKgv8NlYD2gDqcsF
"""

from flask import Flask, jsonify

app = Flask(__name__)

# Sample data for IPL winners
IPL_WINNERS = [
    {"year": 2024, "winner": "Chennai Super Kings"},
    {"year": 2023, "winner": "Gujarat Titans"},
    {"year": 2022, "winner": "Gujarat Titans"},
    {"year": 2021, "winner": "Chennai Super Kings"},
    {"year": 2020, "winner": "Mumbai Indians"},
]

@app.route('/ipl-winners', methods=['GET'])
def get_ipl_winners():
    return jsonify(IPL_WINNERS)

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=5000)